# Generated by Django 2.2 on 2019-05-04 18:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('det_style', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserStyling',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uploaded_image', models.FileField(upload_to='user_uploads')),
                ('selected_mode', models.CharField(max_length=10)),
                ('resulted_image', models.FilePathField(path='F:\\LICENTA\\web_application_licenta\\website_licenta\\media\\results')),
                ('selected_painting', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='det_style.Paintings')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
