# Generated by Django 2.2 on 2019-05-09 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('det_style', '0002_userstyling'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userstyling',
            name='resulted_image',
            field=models.TextField(max_length=255),
        ),
    ]
