# Generated by Django 2.2 on 2019-06-26 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('det_style', '0003_auto_20190510_0038'),
    ]

    operations = [
        migrations.AddField(
            model_name='paintings',
            name='author',
            field=models.CharField(default='autor', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='paintings',
            name='name',
            field=models.CharField(default='Author', max_length=45),
        ),
    ]
